#  ---------说明---------
#  mihomo配置（精简版）
#  作者：AIsouler
#  原仓库：https://github.com/AIsouler/MyClash
#  配置链接：https://raw.githubusercontent.com/AIsouler/MyClash/main/Config/mihomoConfigLite.yaml
#  友情推荐，非常好用、省电且内存占用低的代理软件：https://github.com/appshubcc/Bettbox
#  ---------------------

# --- 锚点定义 (通用属性) ---
proxy_providers_common:
  &proxy_providers_common {
    type: http,
    interval: 86400,
    proxy: DIRECT,
    health-check:
      {
        enable: true,
        url: https://g.cn/generate_204,
        interval: 600,
        lazy: true,
      },
  }

# 全局过滤节点
global_exclude_filter:
  &global_exclude_filter {
    exclude-filter: '群|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|超时|收藏|福利|邀请|好友|失联|选择|剩余|公益|发布|DIZTNA|通路|登录|禁止|定时|渠道|牢记|永久|余额|阁下|本站|刷新|导航|建议|⚠️|@|Expire|http|com',
  }

# 订阅提供者，如果你想要添加多个订阅提供者，可以复制 provider1 的配置块，并修改 url 、 path 和 additional-prefix 字段。
proxy-providers:
  provider1:
    <<: [*proxy_providers_common, *global_exclude_filter]
    url: '' # 此处引号中间填入机场订阅链接
    age-secret-key: '' # 此处填入机场订阅链接解密私钥，如果机场订阅链接需要解密才能使用，请将解密私钥填入引号中间，否则不要改动此项
    path: ./proxy_providers/provider1.yaml
    override:
      additional-prefix: 'p1 | ' # 给节点名称添加前缀，防止不同订阅的节点重名导致出现问题

# 以下是一个示例，各行缩进必须严格对齐provider1
# provider2:
#   <<: [*proxy_providers_common, *global_exclude_filter]
#   url: ''
#   age-secret-key: ''
#   path: ./proxy_providers/provider2.yaml
#   override:
#     additional-prefix: 'p2 | '

# 节点配置，可添加自定义节点
proxies:
  - { name: '🇨🇳 直连 | IPv4优先', type: direct, ip-version: ipv4-prefer }
  - { name: '🇨🇳 直连 | IPv6优先', type: direct, ip-version: ipv6-prefer }
  - { name: '🇨🇳 直连 | 双栈', type: direct }

# --- 基础全局配置 ---

allow-lan: true
ipv6: true
mode: rule
log-level: info
bind-address: '*'
unified-delay: true
tcp-concurrent: true
keep-alive-idle: 600
keep-alive-interval: 60
find-process-mode: strict
external-controller: '127.0.0.1:9090'
external-ui: ui
external-ui-url: 'https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip'

profile:
  store-selected: true
  store-fake-ip: true

# 国内外 DNS 定义
chinaDNS:
  &chinaDNS [
    'https://dns.alidns.com/dns-query#DIRECT',
    'https://doh.pub/dns-query#DIRECT',
  ]
foreignDNS:
  &foreignDNS [
    'https://dns.cloudflare.com/dns-query#默认代理',
    'https://dns.google/dns-query#默认代理',
  ]

dns:
  enable: true
  ipv6: true
  use-hosts: true
  cache-algorithm: arc
  use-system-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: ['rule-set:private', 'rule-set:fakeip_filter']
  proxy-server-nameserver: *chinaDNS
  default-nameserver: ['223.5.5.5', '119.29.29.29']
  nameserver: *foreignDNS
  nameserver-policy:
    'rule-set:cn': *chinaDNS
  direct-nameserver: ['system', '223.5.5.5', '119.29.29.29']

hosts:
  'dns.alidns.com': ['223.5.5.5', '223.6.6.6']
  'doh.pub': ['1.12.12.12', '120.53.53.53']
  'dns.cloudflare.com': ['1.1.1.1', '1.0.0.1']
  'dns.google': ['8.8.8.8', '8.8.4.4']

  # 解决谷歌商店无法下载的问题
  'services.googleapis.cn': ['services.googleapis.com']

  # 屏蔽哔哩哔哩PCDN，解决访问视频卡顿问题
  '+.mcdn.bilivideo.com': ['0.0.0.0']
  '+.mcdn.bilivideo.cn': ['0.0.0.0']
  '+.edge.mountaintoys.cn': ['0.0.0.0']

ntp:
  enable: true
  write-to-system: false
  server: 'ntp.aliyun.com'
  port: 123
  interval: 60

tun:
  enable: true
  stack: system
  auto-route: true
  strict-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack: ['any:53', 'tcp://any:53']

# --- 规则集 ---

# Rule Provider 通用配置
rule_providers_common:
  rule_providers_domain:
    &rule_providers_domain {
      type: http,
      format: mrs,
      interval: 86400,
      behavior: domain,
    }
  rule_providers_ip:
    &rule_providers_ip {
      type: http,
      format: mrs,
      interval: 86400,
      behavior: ipcidr,
    }

# 定义 Rule Providers
rule-providers:
  # --- 直连规则集 ---

  private:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs'
    path: './ruleset/private.mrs'
    path-in-bundle: 'geo/geosite/private.mrs'
  private_ip:
    <<: *rule_providers_ip
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/private.mrs'
    path: './ruleset/private_ip.mrs'
    path-in-bundle: 'geo/geoip/private.mrs'
  games_cn:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-games@cn.mrs'
    path: './ruleset/category-games@cn.mrs'
    path-in-bundle: 'geo/geosite/category-games@cn.mrs'
  epicgames:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/epicgames.mrs'
    path: './ruleset/epicgames.mrs'
    path-in-bundle: 'geo/geosite/epicgames.mrs'
  apple_cn:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/apple@cn.mrs'
    path: './ruleset/apple@cn.mrs'
    path-in-bundle: 'geo/geosite/apple@cn.mrs'
  microsoft_cn:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft@cn.mrs'
    path: './ruleset/microsoft@cn.mrs'
    path-in-bundle: 'geo/geosite/microsoft@cn.mrs'
  cn_additional:
    <<: *rule_providers_domain
    url: 'https://static-file-global.353355.xyz/rules/cn-additional-list.mrs'
    path: './ruleset/cn-additional-list.mrs'
    path-in-bundle: 'geo/geosite/cn.mrs'
  cn_ip:
    <<: *rule_providers_ip
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.mrs'
    path: './ruleset/cn_ip.mrs'
    path-in-bundle: 'geo/geoip/cn.mrs'

  # --- 代理规则集 ---

  ai:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-ai-!cn.mrs'
    path: './ruleset/ai.mrs'
    path-in-bundle: 'geo/geosite/category-ai-!cn.mrs'
  telegram:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/telegram.mrs'
    path: './ruleset/telegram.mrs'
    path-in-bundle: 'geo/geosite/telegram.mrs'
  telegram_ip:
    <<: *rule_providers_ip
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/telegram.mrs'
    path: './ruleset/telegram_ip.mrs'
    path-in-bundle: 'geo/geoip/telegram.mrs'
  google:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/google.mrs'
    path: './ruleset/google.mrs'
    path-in-bundle: 'geo/geosite/google.mrs'
  gfw:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/gfw.mrs'
    path: './ruleset/gfw.mrs'
    path-in-bundle: 'geo/geosite/gfw.mrs'

  # --- 其他规则集 ---

  adblockmihomolite:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/217heidai/adblockfilters@main/rules/adblockmihomolite.mrs'
    path: './ruleset/adblockmihomolite.mrs'
    path-in-bundle: 'geo/geosite/category-ads-all.mrs'
  fakeip_filter:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/wwqgtxx/clash-rules@release/fakeip-filter.mrs'
    path: './ruleset/fakeip-filter.mrs'
    path-in-bundle: 'geo/geosite/private.mrs'
  cn:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/wwqgtxx/clash-rules@release/direct.mrs'
    path: './ruleset/cn.mrs'
    path-in-bundle: 'geo/geosite/cn.mrs'

# --- 策略组 (Proxy Groups) ---

# 策略组通用配置
group_common:
  group_common_select:
    &group_common_select {
      type: select,
      interval: 600,
      timeout: 3000,
      max-failed-times: 3,
      empty-fallback: REJECT,
      url: 'https://g.cn/generate_204',
      lazy: true,
    }

  group_common_auto:
    &group_common_auto {
      type: url-test,
      interval: 600,
      timeout: 3000,
      max-failed-times: 3,
      empty-fallback: REJECT,
      url: 'https://g.cn/generate_204',
      lazy: true,
      tolerance: 50,
      include-all: true,
      exclude-type: 'DIRECT',
      icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png',
      hidden: true,
    }

# 通用代理节点组
proxies_common:
  proxies_default:
    &proxies_default {
      proxies:
        [
          '默认代理',
          '自动选择',
          '香港',
          '日本',
          '美国',
          '新加坡',
          '台湾省',
          '低倍率节点',
          '高倍率节点',
          '其他节点',
        ],
    }

  proxies_direct:
    &proxies_direct {
      proxies:
        [
          '默认代理',
          '自动选择',
          '直连',
          '香港',
          '日本',
          '美国',
          '新加坡',
          '台湾省',
          '低倍率节点',
          '高倍率节点',
          '其他节点',
        ],
    }

  proxies_reject: &proxies_reject { proxies: ['REJECT', 'REJECT-DROP', 'PASS'] }

# 地区过滤器正则表达式定义
group_filter:
  HK_filter: &HK_filter { filter: '🇭🇰|港|HK|[Hh]ong\s*[Kk]ong' }
  JP_filter: &JP_filter { filter: '🇯🇵|日本|JP|[Jj]apan' }
  US_filter: &US_filter { filter: '🇺🇸|美|US|[Aa]merica|[Uu]nited\s*[Ss]tates' }
  SG_filter: &SG_filter { filter: '🇸🇬|新加坡|狮城|SG|[Ss]ingapore' }
  TW_filter: &TW_filter { filter: '🇹🇼|台湾|TW|[Tt]aiwan' }
  low_filter:
    &low_filter {
      filter: '^(?!.*(?:剩|期|客户端|软件)).*(?:(?<!\d)0\.[0-5]|下载|低倍)',
    }
  high_filter:
    &high_filter {
      filter: '(?u)(?:[*×xX✕✖⨉]\s*(?:[2-9]\d*|[1-9]\d+)(?:\.\d+)?)|(?:(?<![\d.])(?:[2-9]\d*|[1-9]\d+)(?:\.\d+)?\s*(?:倍|[*×xX✕✖⨉]))',
    }
  exclude_filter:
    &exclude_filter {
      exclude-filter: '港|HK|🇭🇰|日本|JP|🇯🇵|美|US|🇺🇸|新加坡|SG|🇸🇬|台湾|TW|🇹🇼',
      exclude-type: 'DIRECT',
    }

# 定义分流策略组
proxy-groups:
  - name: '默认代理'
    <<: *group_common_select
    proxies:
      [
        '香港',
        '日本',
        '美国',
        '新加坡',
        '台湾省',
        '低倍率节点',
        '高倍率节点',
        '自动选择',
        '其他节点',
      ]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png'

  - name: '自动选择'
    <<: *group_common_auto

  - name: 'AI'
    <<: [*group_common_select, *proxies_default]
    default-selected: '美国'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/ChatGPT.png'

  - name: 'Telegram'
    <<: [*group_common_select, *proxies_default]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png'

  - name: 'Steam'
    <<: [*group_common_select, *proxies_direct]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png'

  - name: 'AdBlock'
    <<: [*group_common_select, *proxies_reject]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Advertising.png'

  - name: '漏网之鱼'
    <<: *group_common_select
    proxies: ['默认代理', '直连']
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Stack.png'

  - name: '直连'
    <<: *group_common_select
    proxies: ['🇨🇳 直连 | IPv4优先', '🇨🇳 直连 | IPv6优先', '🇨🇳 直连 | 双栈']
    url: 'https://connectivitycheck.platform.hicloud.com/generate_204'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/China_Map.png'

  # 定义地区策略组
  - name: '香港'
    <<: [*group_common_select, *HK_filter]
    include-all: true
    proxies: ['香港-自动选择']
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png'
  - name: '香港-自动选择'
    <<: [*group_common_auto, *HK_filter]

  - name: '日本'
    <<: [*group_common_select, *JP_filter]
    include-all: true
    proxies: ['日本-自动选择']
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png'
  - name: '日本-自动选择'
    <<: [*group_common_auto, *JP_filter]

  - name: '美国'
    <<: [*group_common_select, *US_filter]
    include-all: true
    proxies: ['美国-自动选择']
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png'
  - name: '美国-自动选择'
    <<: [*group_common_auto, *US_filter]

  - name: '新加坡'
    <<: [*group_common_select, *SG_filter]
    include-all: true
    proxies: ['新加坡-自动选择']
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png'
  - name: '新加坡-自动选择'
    <<: [*group_common_auto, *SG_filter]

  - name: '台湾省'
    <<: [*group_common_select, *TW_filter]
    include-all: true
    proxies: ['台湾省-自动选择']
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png'
  - name: '台湾省-自动选择'
    <<: [*group_common_auto, *TW_filter]

  - name: '低倍率节点'
    <<: [*group_common_select, *low_filter]
    include-all: true
    proxies: ['低倍率节点-自动选择']
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available_1.png'
  - name: '低倍率节点-自动选择'
    <<: [*group_common_auto, *low_filter]

  - name: '高倍率节点'
    <<: [*group_common_select, *high_filter]
    include-all: true
    proxies: ['高倍率节点-自动选择']
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Airport.png'
  - name: '高倍率节点-自动选择'
    <<: [*group_common_auto, *high_filter]

  - name: '其他节点'
    <<: [*group_common_select, *exclude_filter]
    include-all: true
    proxies: ['其他节点-自动选择']
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/World_Map.png'
  - name: '其他节点-自动选择'
    <<: [*group_common_auto, *exclude_filter]

# --- 路由规则 (Rules) ---

rules:
  # 禁用国外 QUIC 流量
  - AND,((NETWORK,UDP),(DST-PORT,443),(NOT,((OR,((RULE-SET,cn_additional),(RULE-SET,cn_ip,no-resolve)))))),REJECT

  # 私有网络直连
  - RULE-SET,private,直连
  - RULE-SET,private_ip,直连,no-resolve

  # 国内直连
  - RULE-SET,games_cn,直连 # 已包含 steam 下载域名
  - RULE-SET,epicgames,直连
  - RULE-SET,apple_cn,直连
  - RULE-SET,microsoft_cn,直连
  - DOMAIN,fsend.cn,直连
  - DOMAIN,international-gfe.download.nvidia.com,直连

  # 广告拦截
  - RULE-SET,adblockmihomolite,AdBlock

  # 代理规则
  - RULE-SET,ai,AI
  - RULE-SET,telegram,Telegram
  - RULE-SET,telegram_ip,Telegram,no-resolve
  - RULE-SET,google,默认代理

  # 兜底规则
  - RULE-SET,gfw,默认代理
  - RULE-SET,cn_additional,直连
  - RULE-SET,cn_ip,直连
  - MATCH,漏网之鱼
