name: check_and_fix_format

on:
  push:
    branches: ['main']
    paths:
      - 'Script/*'
      - 'Test/**'
      - '**/*.yaml'
      - '**/*.yml'
      - '.prettierrc*'
  workflow_dispatch:

jobs:
  check_and_fix:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: install tools
        run: |
          npm install -g prettier

      # 格式化 JS（覆写脚本 + Test 测试代码）
      - name: format js files
        run: |
          prettier Script/*.js --write
          prettier "Test/**/*.js" --write

      # 格式化 YAML
      - name: format yaml files
        run: |
          prettier "**/*.{yml,yaml}" --write

      - name: commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          git diff --cached --quiet || (
            git commit -m "chore: auto format"
            git push
          )

  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: run tests
        run: node Test/run-tests.js
